repos:
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        name: ShellCheck
        entry: shellcheck
        language: system
        files: \.sh$
